### PR TITLE
Added Filter Questions by Difficulty Feature

### LINKED ISSUE #36: Add additional filtering option to the filter bar component
Right now, we can only filter by searching for names, 
Addition filtering options should be included in the GUI to allow filtering for difficulty range, question type etc.

The base filtering method has already been provided and currently only the UI for adjusting these filtering constraints is missing. 

Thus, it would be good to include in additional filtering options in the filter bar to support the above-mentioned options. 

note: there should only be changes to `QnFilter` component.

### PR DESCRIPTION
**Pull request by Isaaclhy00**
Added DifficultyFilter component under QnFilter
Added the DifficultyFilter component to BankPage

Closes #36

### CODE REVIEW

**Comment by Isaaclhy00** [comment]
Screenshot 2023-10-28 at 11 11 35 PM
Screenshot 2023-10-28 at 11 12 17 PM
Screenshot 2023-10-28 at 11 12 42 PM

**Review by cheehongw — CHANGES_REQUESTED** [review]

**Review by cheehongw — CHANGES_REQUESTED** [review]
Please don't commit your changes to package.json and package-lock.json if there is no change.

In this case, there is no reason the libraries in `package.json` should change, unless you are installing new libraries

**Comment by cheehongw** [comment]
image

don't just commit a "delete". Instead, please look up how to restore a file to before a particular point in commit history

https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha

**Review by cheehongw — APPROVED** [review]
LGTM

**Pull request merged**
