### PR TITLE
Nice to have: Code execution

### PR DESCRIPTION
**Pull request by Isaaclhy00**
Depends on #61

Added index.ts to handle sending POST request to Judge0 to execute the code and GET request to Judge0 to obtain execution results
Added execute_code.js to call execute() function (to be called when submit button is pressed)

### CODE REVIEW

**Comment by cheehongw** [comment]
image

image

In your PR branch, please remove the `node_modules`,  `package.json` and `package-lock.json` from the root of the project directory. 

I think we accidentally committed a `package.json` in the root level of our repo but it should not be there. Same goes for the `node_modules` and `package-lock.json` - it should never have been generated in the first place.

**Comment by cheehongw** [comment]
Currently, calling one single endpoint will trigger the creation of batched submission, execution of batch submission, and response upon completion of all tasks in the batched submission.

image

**Comment by Eclipse-Dominator** [comment]
- Converted batch execution of test cases to sequential test cases.
- Fixed issue with disconnections and leave match
- Linked frontend submission with the service
- Fixed disconnect not triggering on page route change

- Added GUI for leave match as reconnect match.
image

**Review by cheehongw — APPROVED** [review]
lgtm

**Pull request merged**
