### PR TITLE
Nice to have: Edited ChatBox.component.tsx

### PR DESCRIPTION
**Pull request by Gavzzz**
edited overall design of the chatbox
Chatbox size is now fixed and words will wrap underneath if message length is too long
chatbox will also autoscroll to the last sent message 
used avatar component instead of Tag

### CODE REVIEW

**Comment by cheehongw** [comment]
what does the chatbox look like when two users are chatting?

Also, i think the overall look of the chatbox can be improved by taking inspiration from the many examples available online.

**Comment by Gavzzz** [comment]
Screenshot 2023-11-07 at 11 50 38 AM


Avatar component now takes the initial of the user name to display

**Comment by Gavzzz** [comment]
Screenshot 2023-11-07 at 10 41 53 PM

**Review by cheehongw — APPROVED** [review]
lgtm

**Pull request merged**
